name: setup
description: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
        scope: "@originator-profile"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
