name: setup
description: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: "https://npm.pkg.github.com"
        scope: "@originator-profile"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
