export default {
  sidebar: [
    {
      type: "link",
      label: "Architectural Overview",
      href: "pathname:///aov/",
    },
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};
