name: originator-profile/originator-profile.org/test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    # format ステップで新しいコミットを push するために write 権限を与える
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup
        uses: "./.github/actions/setup"
      - name: Format
        uses: "originator-profile/originator-profile/.github/actions/format@4433e3301df08b60345aeb768a85f8f75b1a2224" # main
