name: originator-profile/originator-profile.org/test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    # format ステップで新しいコミットを push するために write 権限を与える
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Setup
        uses: "./.github/actions/setup"
      - name: Format
        uses: "originator-profile/originator-profile/.github/actions/format@4d86b5fba80c22d2a332910775b55bbf022e9a78" # main
